export const KITS = {
  courier: {
    name: "Courier",
    role: "Balanced equipment",
    passive: "Balanced hull, blade and pulse reserves.",
    hp: 18,
    attack: 3,
    charges: 2,
    maxCharges: 3,
    pulseDamage: 4,
  },
  relay: {
    name: "Relay",
    role: "Pulse specialist",
    passive: "A pulse that kills 2+ hostiles refunds 1 charge.",
    hp: 14,
    attack: 2,
    charges: 3,
    maxCharges: 4,
    pulseDamage: 5,
    goal: { stat: "kills", target: 10, label: "kills" },
  },
  breaker: {
    name: "Breaker",
    role: "Close combat survivor",
    passive: "Every melee kill repairs 1 hull.",
    hp: 24,
    attack: 4,
    charges: 1,
    maxCharges: 2,
    pulseDamage: 3,
    goal: { stat: "districts", target: 3, label: "districts" },
  },
};
